---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopstest-stagged
  namespace: stagged
  labels:
    app: devopstest-stagged
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopstest-stagged
  template:
    metadata:
      labels:
        app: devopstest-stagged
    spec:
      imagePullSecrets:
        - name: regcred
        - name: registry-crt
      containers:
        - name: devopstest-stagged
          image: panzdb1.world:443/laraveltest:staggedV1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: devopstest-stagged-service
  namespace: stagged
spec:
  type: LoadBalancer
  selector:
    app: devopstest-stagged
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000