---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopstest-prod
  namespace: prod
  labels:
    app: devopstest-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopstest-prod
  template:
    metadata:
      labels:
        app: devopstest-prod
    spec:
      imagePullSecrets:
        - name: regcred
        - name: registry-crt
      containers:
        - name: devopstest-prod
          image: panzdb1.world:443/laraveltest:prodV1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: devopstest-prod-service
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: devopstest-prod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000