---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopstest-devel
  namespace: devel
  labels:
    app: devopstest-devel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopstest-devel
  template:
    metadata:
      labels:
        app: devopstest-devel
    spec:
      imagePullSecrets:
        - name: regcred
        - name: registry-crt
      containers:
        - name: devopstest-devel
          image: panzdb1.world:443/laraveltest:develV1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: devopstest-devel-service
  namespace: devel
spec:
  type: LoadBalancer
  selector:
    app: devopstest-devel
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000